In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv("/Users/koshidatatsuo/python/kaggle/Deep_Past_Challenge/data/kaggle/deep-past-initiative-machine-translation/train.csv")

In [3]:
train_df.head()

,oare_id,transliteration,translation
0,004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-{d}IM KIŠI...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ..."
1,0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé,Itūr-ilī has received one textile of ordinary ...
2,0073f2c0-524c-4bbf-915a-8c1772a4fb98,TÚG u-la i-dí-na-ku-um i-tù-ra-ma 9 GÍN KÙ.BABBAR,<gap> he did not give you a textile. He return...
3,009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-{d}EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"Seal of Šu-Illil son of Šu-Kūbum, seal of Ṣilū..."
4,00aa1c55-c80c-4346-a159-73ad43ab0ff7,um-ma šu-ku-tum-ma a-na IŠTAR-lá-ma-sí ù ni-ta...,From Šukkutum to Ištar-lamassī and Nitahšušar:...

In [4]:
len(train_df)

1561

In [ ]:
# ソース：https://www.kaggle.com/competitions/deep-past-initiative-machine-translation/discussion/678899#3415774
pub_pd = pd.read_csv("/Users/koshidatatsuo/python/kaggle/Deep_Past_Challenge/data/kaggle/deep-past-initiative-machine-translation/published_texts.csv")

train_df = pd.read_csv("/Users/koshidatatsuo/python/kaggle/Deep_Past_Challenge/data/kaggle/deep-past-initiative-machine-translation/train.csv")

akt_pd = pub_pd[(pub_pd['oare_id'].isin(train_df["oare_id"].unique()))][["oare_id", "label", "excavation_no", "transliteration"]]
akt_pd["pdf"] = akt_pd["label"].str.extract(
    r"\bAKT\s+(\d+[a-zA-Z]?)",
    expand=False
)

In [6]:
akt_pd

,oare_id,label,excavation_no,transliteration,pdf
112,01cc1406-fc42-4252-aeae-6b4538b069c5,Cuneiform Tablet Kt 92/k 239 (AKT 5 57),Kt 92/k 239,17 GÍN KÙ.BABBAR ší-im e-ma-ri-im 30 ma-na URU...,5
114,017c5be4-f459-4ef5-a045-5933e79c01f9,Cuneiform Tablet Kt 92/k 245 (AKT 5 69),Kt 92/k 245,ṭup-pu-um ša 10 ma-na KÙ.BABBAR ša PÚZUR-a-šur...,5
115,f52c21e6-5eb4-4a73-a539-c2686cc935b8,Cuneiform Tablet Kt 89/k 289 (AKT 5 76),Kt 89/k 289,a-na ku-li-a qí-bi4-ma um-ma a-šùr-i-mì-tí-ma ...,5
116,0126cd13-acf7-4cd5-8373-f1e7b54d824e,Cuneiform Tablet Kt 94/k 943 (AKT 6a 106),Kt 94/k 943,a-na É šál-ma-a-šùr a-na a-wa-tim né-ru-ub-ma ...,6a
117,00f0d841-eb7a-46f8-86fc-bf9fd7d52cbf,Cuneiform Tablet Kt 94/k 863B (AKT 6a 235),Kt 94/k 863B,um-ma šu-ta-mu-zi e-lá-a en-um-a-šùr ù lá-ma-s...,6a
...,...,...,...,...,...
7825,4cce0418-d5ac-4331-9793-a99d9efe2fce,Cuneiform Tablet Kt 91/k 504 (AKT 8 197),Kt 91/k 504,2 GÍN KÙ.KI ku-pu-ur-ší-ni-IN SIG5 i-ṣé-er im-...,8
7851,cdc5019e-3950-488f-954d-1900a0e02308,Cuneiform Tablet Kt 91/k 530 (AKT 8 18),Kt 91/k 530,a-na a-šur-re-ṣí da-dí-a ù en-nam-a-šur qí-bi4...,8
7852,e20adb01-f24e-47f9-a1b5-3bc88b888800,Cuneiform Tablet Kt 91/k 317 (AKT 8 79),Kt 91/k 317,a-na a-šur-re-ṣí en-um-a-šur da-dí-a ú a-ta-a ...,8
7898,781849b2-3db5-423b-ae57-a9f2047af627,Cuneiform Tablet Kt 91/k 402 (AKT 8 287),Kt 91/k 402,KIŠIB a-šur-ṣú-lu-li DUMU šu-lá-ba-an KIŠIB a-...,8
7935,262d446e-3fb6-4e13-83b2-9c0348714d58,Cuneiform Tablet Kt 94/k 1385 (AKT 6c 637),Kt 94/k 1385,um-ma a-šur-{d}UTU-ši ù da-da-a-ma a-na a-lá-ḫ...,6c

In [9]:
akt_pd.to_csv("../../data/expand_train.csv")